"""Deterministic, local-only navigation over a MyResourceCenter snapshot.

This module deliberately does not call Google Drive or any hosted retrieval
service.  It selects compact reference metadata and structured Evidence from a
snapshot generated by MyResourceCenter.  The selected text is untrusted
reference data.
"""

from __future__ import annotations

import hashlib
import json
import re
import unicodedata
from pathlib import Path
from typing import Any, Mapping


SNAPSHOT_SCHEMA_VERSION = "1.0.0"
SNAPSHOT_KIND = "myresourcecenter-reference-snapshot"
SELECTION_SCHEMA_VERSION = "1.0.0"
DEFAULT_MAX_ITEMS = 5
DEFAULT_MAX_CONTEXT_CHARACTERS = 8000
MAX_QUERY_CHARACTERS = 4096
_LATIN_TOKEN_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_./:+-]{1,}")
_CJK_RUN_RE = re.compile(r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uff66-\uff9f]{2,}")


class ReferenceSnapshotError(ValueError):
    """Raised when a local snapshot cannot be safely used."""


def _normalise(value: Any) -> str:
    return unicodedata.normalize("NFKC", str(value or "")).casefold().strip()


def _terms(value: Any) -> set[str]:
    """Return stable Latin tokens and short Japanese n-grams.

    A word tokenizer alone misses Japanese queries.  The n-grams are used only
    for deterministic candidate navigation; the source facts remain untouched.
    """

    text = _normalise(value)
    result = set(_LATIN_TOKEN_RE.findall(text))
    for match in _CJK_RUN_RE.findall(text):
        result.add(match)
        for size in (2, 3):
            if len(match) < size:
                continue
            result.update(match[index : index + size] for index in range(len(match) - size + 1))
    return {item for item in result if len(item) >= 2}


def _as_text_list(value: Any) -> list[str]:
    if isinstance(value, str):
        return [value.strip()] if value.strip() else []
    if not isinstance(value, list):
        return []
    return [str(item).strip() for item in value if str(item).strip()]


def _load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ReferenceSnapshotError(f"cannot read reference snapshot: {path}") from exc
    if not isinstance(value, dict):
        raise ReferenceSnapshotError("reference snapshot must be a JSON object")
    return value


def _validate_snapshot(snapshot: Mapping[str, Any]) -> None:
    if snapshot.get("schema_version") != SNAPSHOT_SCHEMA_VERSION:
        raise ReferenceSnapshotError("unsupported reference snapshot schema")
    if snapshot.get("kind") != SNAPSHOT_KIND:
        raise ReferenceSnapshotError("unexpected reference snapshot kind")
    policy = snapshot.get("source_policy")
    if not isinstance(policy, Mapping) or policy.get("raw_document_body_included") is not False:
        raise ReferenceSnapshotError("snapshot must not contain raw document body")
    for field in ("resources", "collections", "relations", "evidence_documents"):
        if not isinstance(snapshot.get(field), list):
            raise ReferenceSnapshotError(f"snapshot field must be an array: {field}")


def load_snapshot(path: str | Path) -> dict[str, Any]:
    snapshot = _load_json(Path(path))
    _validate_snapshot(snapshot)
    return snapshot


def _resource_eligible(resource: Mapping[str, Any], tier: str) -> bool:
    eligibility = resource.get("eligibility")
    if not isinstance(eligibility, Mapping):
        return False
    if tier not in {"default", "investigation"}:
        raise ReferenceSnapshotError("tier must be default or investigation")
    return eligibility.get(tier) is True


def _collection_map(snapshot: Mapping[str, Any]) -> dict[str, Mapping[str, Any]]:
    result: dict[str, Mapping[str, Any]] = {}
    for collection in snapshot.get("collections", []):
        if isinstance(collection, Mapping) and isinstance(collection.get("collection_id"), str):
            result[collection["collection_id"]] = collection
    return result


def _source_quality(candidate: Mapping[str, Any]) -> float:
    if candidate.get("kind") == "evidence_document":
        return 1.0
    confidence = _normalise(candidate.get("confidence"))
    confidence_weight = {"high": 1.0, "medium": 0.85, "low": 0.65, "unverified": 0.5}.get(confidence, 0.5)
    review_weight = 1.0 if _normalise(candidate.get("review_state")) == "reviewed" else 0.72
    return round(confidence_weight * review_weight, 3)


def _candidate_fields(candidate: Mapping[str, Any], collections: Mapping[str, Mapping[str, Any]]) -> dict[str, list[str]]:
    fields = {
        "title": _as_text_list(candidate.get("title")),
        "summary": _as_text_list(candidate.get("summary")),
        "topics": _as_text_list(candidate.get("topics")),
        "tags": _as_text_list(candidate.get("tags")),
        "facts": [],
        "collections": [],
    }
    if candidate.get("kind") == "resource":
        fields["facts"] = _as_text_list(candidate.get("key_facts"))
        for collection_id in _as_text_list(candidate.get("collection_ids")):
            collection = collections.get(collection_id)
            if collection:
                fields["collections"].extend(
                    _as_text_list(collection.get("title"))
                    + _as_text_list(collection.get("description"))
                    + _as_text_list(collection.get("topics"))
                )
    else:
        fields["facts"] = [
            str(item.get("fact"))
            for item in candidate.get("facts", [])
            if isinstance(item, Mapping) and str(item.get("fact") or "").strip()
        ]
    return fields


def _score_candidate(
    candidate: Mapping[str, Any], query_terms: set[str], collections: Mapping[str, Mapping[str, Any]], query: str
) -> tuple[float, list[str]]:
    fields = _candidate_fields(candidate, collections)
    weights = {"title": 12.0, "summary": 7.0, "topics": 8.0, "tags": 7.0, "facts": 5.0, "collections": 3.0}
    score = 0.0
    matched: set[str] = set()
    for field_name, values in fields.items():
        field_terms: set[str] = set()
        for value in values:
            field_terms |= _terms(value)
        overlap = query_terms & field_terms
        if overlap:
            matched.update(overlap)
            score += min(4, len(overlap)) * weights[field_name]
    normalized_query = _normalise(query)
    normalized_title = _normalise(candidate.get("title"))
    normalized_summary = _normalise(candidate.get("summary"))
    if normalized_query and normalized_query in normalized_title:
        score += 20.0
    elif normalized_query and normalized_query in normalized_summary:
        score += 8.0
    score *= _source_quality(candidate)
    return round(score, 3), sorted(matched)


def _resource_candidate(resource: Mapping[str, Any], score: float, matched: list[str], collections: Mapping[str, Mapping[str, Any]], *, related: bool = False, related_from: str | None = None) -> dict[str, Any]:
    collection_titles = []
    for collection_id in _as_text_list(resource.get("collection_ids")):
        collection = collections.get(collection_id)
        if collection and collection.get("title"):
            collection_titles.append(str(collection["title"]))
    return {
        "candidate_id": str(resource.get("resource_id")),
        "kind": "resource",
        "title": str(resource.get("title") or ""),
        "summary": str(resource.get("summary") or ""),
        "topics": _as_text_list(resource.get("topics")),
        "tags": _as_text_list(resource.get("tags")),
        "key_facts": _as_text_list(resource.get("key_facts")),
        "source": {
            "source_uri": resource.get("source_uri"),
            "drive_file_id": resource.get("drive_file_id"),
        },
        "collection_ids": _as_text_list(resource.get("collection_ids")),
        "collection_titles": collection_titles,
        "relation_refs": resource.get("relation_refs", []),
        "review_state": resource.get("review_state"),
        "use_state": resource.get("use_state"),
        "confidence": resource.get("confidence"),
        "freshness": resource.get("freshness"),
        "score": score,
        "matched_terms": matched,
        "selection_reason": "related_one_hop" if related else "lexical_catalog_match",
        "related_from": related_from,
        "untrusted_reference": True,
    }


def _evidence_candidate(document: Mapping[str, Any], score: float, matched: list[str]) -> dict[str, Any]:
    source = document.get("source") if isinstance(document.get("source"), Mapping) else {}
    facts = [
        {
            "evidence_id": str(item.get("evidence_id") or ""),
            "kind": str(item.get("kind") or "evidence"),
            "fact": str(item.get("fact") or ""),
            "source_units": [unit for unit in item.get("source_units", []) if isinstance(unit, int) and unit > 0],
        }
        for item in document.get("facts", [])
        if isinstance(item, Mapping) and str(item.get("fact") or "").strip()
    ]
    return {
        "candidate_id": str(document.get("document_id")),
        "kind": "evidence_document",
        "title": str(document.get("title") or ""),
        "summary": str(document.get("summary") or ""),
        "topics": _as_text_list(document.get("topics")),
        "tags": [],
        "key_facts": [],
        "facts": facts,
        "source": {
            "source_uri": source.get("source_uri"),
            "drive_file_id": source.get("drive_file_id"),
            "file_name": source.get("file_name"),
            "workspace_path": source.get("workspace_path"),
            "source_units": sorted({unit for item in facts for unit in item["source_units"]}),
        },
        "resource_id": document.get("resource_id"),
        "reference_status": document.get("reference_status"),
        "score": score,
        "matched_terms": matched,
        "selection_reason": "lexical_evidence_match",
        "untrusted_reference": True,
    }


def _expand_related(
    direct: list[dict[str, Any]],
    resources: Mapping[str, Mapping[str, Any]],
    collections: Mapping[str, Mapping[str, Any]],
    tier: str,
    limit: int,
) -> list[dict[str, Any]]:
    existing = {item["candidate_id"] for item in direct}
    expanded: list[dict[str, Any]] = []
    for item in direct[:3]:
        if item.get("kind") != "resource":
            continue
        for relation in item.get("relation_refs", []):
            if not isinstance(relation, Mapping):
                continue
            related_id = relation.get("resource_id")
            related = resources.get(str(related_id)) if related_id else None
            if (
                not related
                or not _resource_eligible(related, tier)
                or str(related_id) in existing
                or any(x["candidate_id"] == str(related_id) for x in expanded)
            ):
                continue
            expanded.append(
                _resource_candidate(
                    related,
                    round(float(item["score"]) * 0.35, 3),
                    [],
                    collections,
                    related=True,
                    related_from=item["candidate_id"],
                )
            )
            if len(expanded) >= limit:
                return expanded
    return expanded


def _context_block(candidates: list[Mapping[str, Any]], max_characters: int) -> tuple[str, int, bool]:
    blocks: list[str] = []
    consumed = 0
    truncated = False
    for index, candidate in enumerate(candidates, start=1):
        lines = [
            f"[REFERENCE {index}] {candidate.get('candidate_id')} ({candidate.get('kind')})",
            f"Title: {candidate.get('title', '')}",
            f"Summary: {candidate.get('summary', '')}",
        ]
        topics = _as_text_list(candidate.get("topics"))
        tags = _as_text_list(candidate.get("tags"))
        if topics:
            lines.append("Topics: " + ", ".join(topics))
        if tags:
            lines.append("Tags: " + ", ".join(tags))
        if candidate.get("collection_titles"):
            lines.append("Collections: " + ", ".join(_as_text_list(candidate.get("collection_titles"))))
        facts = candidate.get("key_facts") or [item.get("fact") for item in candidate.get("facts", []) if isinstance(item, Mapping)]
        for fact in _as_text_list(facts)[:4]:
            lines.append("Fact: " + fact)
        source = candidate.get("source") if isinstance(candidate.get("source"), Mapping) else {}
        if source.get("source_uri"):
            lines.append("Source: " + str(source["source_uri"]))
        if source.get("source_units"):
            lines.append("Source units: " + ", ".join(map(str, source["source_units"])))
        block = "\n".join(lines)
        separator = "\n\n" if blocks else ""
        remaining = max_characters - consumed - len(separator)
        if remaining <= 0:
            truncated = True
            break
        if len(block) > remaining:
            block = block[:remaining].rstrip()
            truncated = True
        blocks.append(separator + block)
        consumed += len(separator) + len(block)
        if truncated:
            break
    return "".join(blocks), consumed, truncated


def search_snapshot(
    snapshot: Mapping[str, Any],
    query: str,
    *,
    tier: str = "default",
    max_items: int = DEFAULT_MAX_ITEMS,
    max_context_characters: int = DEFAULT_MAX_CONTEXT_CHARACTERS,
    include_relations: bool = True,
) -> dict[str, Any]:
    _validate_snapshot(snapshot)
    if not isinstance(query, str) or not query.strip():
        raise ReferenceSnapshotError("query must not be empty")
    if len(query) > MAX_QUERY_CHARACTERS:
        raise ReferenceSnapshotError("query exceeds the maximum length")
    if not 1 <= max_items <= 20:
        raise ReferenceSnapshotError("max_items must be between 1 and 20")
    if not 256 <= max_context_characters <= 16000:
        raise ReferenceSnapshotError("max_context_characters must be between 256 and 16000")
    query_terms = _terms(query)
    if not query_terms:
        raise ReferenceSnapshotError("query has no searchable terms")
    collections = _collection_map(snapshot)
    resources = {
        str(item.get("resource_id")): item
        for item in snapshot.get("resources", [])
        if isinstance(item, Mapping) and item.get("resource_id")
    }
    candidates: list[dict[str, Any]] = []
    for resource in resources.values():
        if not _resource_eligible(resource, tier):
            continue
        score, matched = _score_candidate(resource, query_terms, collections, query)
        if score > 0:
            candidates.append(_resource_candidate(resource, score, matched, collections))
    for document in snapshot.get("evidence_documents", []):
        if not isinstance(document, Mapping):
            continue
        score, matched = _score_candidate({**document, "kind": "evidence_document"}, query_terms, collections, query)
        if score > 0:
            candidates.append(_evidence_candidate(document, score, matched))

    candidates.sort(key=lambda item: (-float(item["score"]), item["candidate_id"]))
    direct = candidates[:max_items]
    if include_relations and len(direct) < max_items:
        candidates.extend(_expand_related(direct, resources, collections, tier, max_items - len(direct)))
    candidates.sort(key=lambda item: (-float(item["score"]), item["selection_reason"], item["candidate_id"]))
    selected = candidates[:max_items]
    context, consumed, truncated = _context_block(selected, max_context_characters)
    status = "success" if selected else "empty"
    next_action = "use_local_snapshot" if selected and float(selected[0]["score"]) >= 8 else "recheck_myresourcecenter"
    return {
        "schema_version": SELECTION_SCHEMA_VERSION,
        "kind": "local-reference-selection",
        "status": status,
        "query": query,
        "tier": tier,
        "snapshot_revision": snapshot.get("snapshot_revision"),
        "candidate_count": len(candidates),
        "returned_count": len(selected),
        "candidates": [dict(item, rank=index) for index, item in enumerate(selected, start=1)],
        "context": context,
        "context_characters": consumed,
        "context_truncated": truncated,
        "next_action": next_action,
        "remote_recheck_recommended": next_action == "recheck_myresourcecenter",
        "raw_document_body_included": False,
        "untrusted_reference": True,
    }


def _verification_checks(query: str, candidate: Mapping[str, Any]) -> list[dict[str, Any]]:
    signals = _as_text_list(candidate.get("topics")) + _as_text_list(candidate.get("tags")) + _as_text_list(candidate.get("matched_terms"))
    signal_text = ", ".join(signals[:10]) or "候補資料のタイトル"
    rendering_hint = any(
        term in _normalise(" ".join(signals))
        for term in ("shader", "render", "urp", "描画", "シェーダ", "光", "taa", "motion")
    )
    target = "Shader、Material、Renderer Feature、Render Pipeline設定" if rendering_hint else "関連するスクリプト、設定、アセット、ログ"
    return [
        {
            "step": 1,
            "kind": "local_search",
            "action": f"ローカルプロジェクト内で候補語（{signal_text}）を検索し、{target}の実体と参照経路を特定する。",
            "expected_observation": "候補語に一致するファイル、設定、アセット、参照関係の有無。",
            "cost": "low",
            "mutation": "none",
        },
        {
            "step": 2,
            "kind": "configuration_inspection",
            "action": f"症状が発生する環境・シーン・再現条件を固定し、{target}の現在値を読み取り専用で確認する。",
            "expected_observation": "想定値との差分、未設定値、バージョン／パイプライン依存、または該当なし。",
            "cost": "low",
            "mutation": "none",
        },
        {
            "step": 3,
            "kind": "runtime_observation",
            "action": "最小の再現手順でConsole、画面、Frame Debugger、Profilerなど利用可能な観測結果を取得し、症状と候補の因果関係を切り分ける。",
            "expected_observation": "候補を支持する観測、反証する観測、または観測不能状態。",
            "cost": "medium",
            "mutation": "none",
        },
        {
            "step": 4,
            "kind": "minimal_safe_test",
            "action": "変更を加えずに実行できる最小Test／再現ケースを選び、結果を候補仮説ごとに記録する。",
            "expected_observation": "再現・非再現、発生条件、ログ／キャプチャの差分。",
            "cost": "medium",
            "mutation": "none",
        },
    ]


def build_investigation_plan(
    snapshot: Mapping[str, Any],
    symptom: str,
    *,
    environment: str = "",
    max_hypotheses: int = 5,
    max_context_characters: int = 12000,
) -> dict[str, Any]:
    if not isinstance(symptom, str) or not symptom.strip():
        raise ReferenceSnapshotError("symptom must not be empty")
    if not 1 <= max_hypotheses <= 10:
        raise ReferenceSnapshotError("max_hypotheses must be between 1 and 10")
    query = " ".join(part.strip() for part in (symptom, environment) if part.strip())
    selection = search_snapshot(
        snapshot,
        query,
        tier="investigation",
        max_items=max(5, max_hypotheses * 2),
        max_context_characters=max_context_characters,
        include_relations=True,
    )
    hypotheses: list[dict[str, Any]] = []
    for candidate in selection["candidates"]:
        quality = _source_quality(candidate)
        relevance = float(candidate.get("score", 0.0))
        priority_score = round(relevance * quality, 3)
        source = candidate.get("source") if isinstance(candidate.get("source"), Mapping) else {}
        hypotheses.append(
            {
                "hypothesis_id": "hyp-" + hashlib.sha256(f"{selection['snapshot_revision']}:{candidate['candidate_id']}".encode()).hexdigest()[:12],
                "candidate_id": candidate["candidate_id"],
                "rank": 0,
                "priority_score": priority_score,
                "priority_basis": "catalog/evidence relevance × source quality; this is not a measured probability",
                "hypothesis": (
                    f"症状は『{candidate['title']}』が扱う領域（{', '.join(candidate.get('topics') or candidate.get('tags') or ['関連領域'])}）"
                    "と関係している可能性がある。原因確定ではなく、ローカル観測で検証する候補。"
                ),
                "why_selected": {
                    "matched_terms": candidate.get("matched_terms", []),
                    "summary": candidate.get("summary", ""),
                    "source_quality": quality,
                },
                "checks": _verification_checks(query, candidate),
                "source": {
                    "candidate_id": candidate["candidate_id"],
                    "source_uri": source.get("source_uri"),
                    "drive_file_id": source.get("drive_file_id"),
                    "source_units": source.get("source_units", []),
                    "reference_status": candidate.get("reference_status") or candidate.get("review_state"),
                },
                "mutation_allowed": False,
                "untrusted_reference": True,
            }
        )
    hypotheses.sort(key=lambda item: (-item["priority_score"], item["candidate_id"]))
    for index, hypothesis in enumerate(hypotheses[:max_hypotheses], start=1):
        hypothesis["rank"] = index
    hypotheses = hypotheses[:max_hypotheses]
    plan_payload = f"{selection['snapshot_revision']}|{symptom}|{environment}|" + ",".join(item["candidate_id"] for item in hypotheses)
    return {
        "schema_version": "1.0.0",
        "kind": "local-investigation-plan",
        "plan_id": "plan-" + hashlib.sha256(plan_payload.encode("utf-8")).hexdigest()[:16],
        "symptom": symptom,
        "environment": environment,
        "snapshot_revision": selection["snapshot_revision"],
        "search": selection,
        "hypotheses": hypotheses,
        "ordering_note": "優先順位は関連度・根拠品質・確認コストを用いた切り分け順であり、原因確率の統計的推定ではない。",
        "operating_mode": "local_project_observation_first",
        "remote_recheck_when": [
            "snapshotに該当候補がない",
            "snapshotの情報が古い",
            "原文のページ／スライド確認が必要",
            "候補資料同士が矛盾する",
        ],
        "stop_conditions": [
            "反証が得られた仮説の深掘りを止め、次の仮説へ進む",
            "観測不能を原因確定として扱わない",
            "承認なしに修正・設定変更・破壊的操作を行わない",
        ],
    }
