"""Embedding seams for Qdrant without a mandatory model dependency."""

from __future__ import annotations

from collections import Counter
from collections.abc import Mapping
from dataclasses import dataclass
import hashlib
import math
import re
from typing import Protocol


_TOKEN_RE = re.compile(r"[A-Za-z0-9_][A-Za-z0-9_+.:-]*|[^\W_]+", re.UNICODE)


def tokenize_for_embedding(text: str) -> tuple[str, ...]:
    return tuple(dict.fromkeys(match.casefold() for match in _TOKEN_RE.findall(str(text)) if match.strip()))


class DenseEmbedder(Protocol):
    revision: str
    dimension: int

    def embed_query(self, text: str) -> list[float]: ...

    def embed_document(self, text: str) -> list[float]: ...


class SparseEncoder(Protocol):
    revision: str

    def encode(self, text: str) -> dict[str, list[float] | list[int]]: ...


@dataclass(frozen=True)
class HashingDenseEmbedder:
    """Deterministic offline dense seam for tests and local demonstrations.

    This is a hashing baseline, not a semantic model. Production callers should
    inject their approved embedding provider and set ``embedding_model`` in the
    Qdrant configuration.
    """

    dimension: int = 384
    revision: str = "hashing-dense-v1"

    def __post_init__(self) -> None:
        if not 8 <= int(self.dimension) <= 65_536:
            raise ValueError("hashing dense dimension must be 8..65536")

    def _embed(self, text: str) -> list[float]:
        values = [0.0] * int(self.dimension)
        for token in tokenize_for_embedding(text):
            digest = hashlib.blake2b(token.encode("utf-8"), digest_size=16).digest()
            index = int.from_bytes(digest[:8], "big") % int(self.dimension)
            sign = 1.0 if digest[8] & 1 else -1.0
            values[index] += sign
        norm = math.sqrt(sum(value * value for value in values))
        return [value / norm for value in values] if norm else values

    def embed_query(self, text: str) -> list[float]:
        return self._embed(text)

    def embed_document(self, text: str) -> list[float]:
        return self._embed(text)


@dataclass(frozen=True)
class BM25SparseEncoder:
    """Query-side BM25-compatible sparse encoding.

    The IDF map can be generated by the ingestion pipeline. Unknown terms keep
    weight 1.0 so technical identifiers remain searchable instead of being
    silently discarded.
    """

    idf: Mapping[str, float] | None = None
    revision: str = "bm25-sparse-v1"
    k1: float = 1.2
    b: float = 0.75
    max_terms: int = 256

    def __post_init__(self) -> None:
        if float(self.k1) < 0 or not 0 <= float(self.b) <= 1:
            raise ValueError("BM25 k1 must be non-negative and b must be 0..1")
        if not 1 <= int(self.max_terms) <= 4096:
            raise ValueError("BM25 max_terms must be 1..4096")

    @staticmethod
    def _term_index(token: str) -> int:
        return int.from_bytes(hashlib.blake2b(token.encode("utf-8"), digest_size=8).digest(), "big") % 2_147_483_647

    def encode(self, text: str) -> dict[str, list[float] | list[int]]:
        tokens = tokenize_for_embedding(text)
        counts = Counter(tokens)
        idf = self.idf or {}
        pairs: list[tuple[int, float]] = []
        for token, frequency in counts.items():
            term_id = self._term_index(token)
            weight = float(idf.get(token, 1.0)) * ((frequency * (float(self.k1) + 1.0)) / (frequency + float(self.k1)))
            if weight > 0:
                pairs.append((term_id, weight))
        pairs.sort(key=lambda item: item[0])
        pairs = pairs[: int(self.max_terms)]
        return {
            "indices": [index for index, _ in pairs],
            "values": [round(value, 8) for _, value in pairs],
        }


__all__ = [
    "BM25SparseEncoder",
    "DenseEmbedder",
    "HashingDenseEmbedder",
    "SparseEncoder",
    "tokenize_for_embedding",
]
