#!/usr/bin/env python3
"""Build, incrementally update, or check the deterministic Context Index."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from typing import Any

import yaml


BUILDER_VERSION = "1.0.0"
SCHEMA_VERSION = "1.0"
INDEX_PATH = Path(".ai/context-metadata-index.yaml")
PACK_DIR = Path(".ai/context-packs")


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path: Path) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def entry_from_pack(path: Path, document: dict[str, Any], source_hash: str) -> dict[str, Any]:
    metadata = document["metadata"]
    return {
        "id": document["id"],
        "title": metadata["title"],
        "summary": list(metadata["summary"]),
        "priority": metadata["priority"],
        "tags": sorted(metadata.get("tags", [])),
        "related": sorted(
            [
                {"id": item["id"], "relation": item["relation"]}
                for item in metadata.get("related", [])
            ],
            key=lambda item: (item["id"], item["relation"]),
        ),
        "pack_path": path.as_posix(),
        "source_sha256": source_hash,
    }


def build_index(root: Path, changed_only: bool = False) -> dict[str, Any]:
    existing: dict[str, dict[str, Any]] = {}
    index_path = root / INDEX_PATH
    if changed_only and index_path.is_file():
        current = load(index_path)
        if (
            current.get("schema_version") == SCHEMA_VERSION
            and current.get("builder_version") == BUILDER_VERSION
        ):
            existing = {str(item["pack_path"]): item for item in current.get("contexts", [])}

    entries: list[dict[str, Any]] = []
    for path in sorted((root / PACK_DIR).glob("*.yaml")):
        relative = path.relative_to(root).as_posix()
        source_hash = sha256(path)
        cached = existing.get(relative)
        if cached and cached.get("source_sha256") == source_hash:
            entries.append(cached)
        else:
            entries.append(entry_from_pack(path.relative_to(root), load(path), source_hash))
    entries.sort(key=lambda item: item["id"])
    return {
        "schema_version": SCHEMA_VERSION,
        "generated": True,
        "source_of_truth": False,
        "builder_version": BUILDER_VERSION,
        "contexts": entries,
    }


def serialize(index: dict[str, Any]) -> str:
    return yaml.safe_dump(index, allow_unicode=True, sort_keys=False, default_flow_style=False)


def main() -> int:
    parser = argparse.ArgumentParser()
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--full", action="store_true")
    modes.add_argument("--changed", action="store_true")
    modes.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    index_path = root / INDEX_PATH
    generated = serialize(build_index(root, changed_only=args.changed))
    if args.check:
        if not index_path.is_file():
            print(f"Stale Context Metadata Index: missing {INDEX_PATH}")
            return 1
        expected = index_path.read_text(encoding="utf-8")
        if generated != expected:
            print("Stale Context Metadata Index: generated bytes differ")
            return 1
        print("Context Metadata Index is current.")
        return 0
    index_path.write_text(generated, encoding="utf-8")
    print(f"Wrote {INDEX_PATH} with {len(build_index(root, changed_only=args.changed)['contexts'])} contexts.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
